# Generated by Django 5.0.6 on 2024-08-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='borrowing_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
